#无图探索local_planner参数配置
localPlanner:
  vehicleWidth: 0.62        # 车宽
  vehicleLength: 0.6        # 车长
  add_point_radius: 0.25    # 障碍物最大膨胀半径
  minPathRange: 0.62        # 最小规划范围
  goalClearRange: 0.45      # 快到目的地时减小障碍物检测的范围
  slow_dis: 0.9             # 近障减速距离
  obstacleHeightThre: 0.09  # 地形分析中，intensity的筛选阈值


pathFollower:
  endGoalDis: 0.4         # 到达目标点范围内就停止
  use_closeGoal_direct: false  # 开启到目标点附近的精确到点模式（在靠近目标0.6m时会关闭避障）
  useCloudSlowDown: true  # 使能根据周围障碍物点云密集情况进行减速
  slowdown_rate: 0.65     # 根据周围障碍物进行减速的比例
  minSpeed: 0.1           # 加减速死区阈值
  maxAddAccel: 3.0        # 最大加速加速度
  maxSlowAccel: 4.0       # 最大减速加速度
  use_getgoal_yaw: false  # 允许控制到目标点时的车头朝向
  getgoal_yaw: 0.0        # 到目标点时的车头相对世界坐标系的朝向


usualParams:
  maxSpeed: 0.7               # 整车最大速度
  use_relocalization: false   # 是否使用重定位调整到同一个地图坐标系
  use_map: false              # 是否使用先验地图
  use_prior_path: false       # 是否使用先验路径


nav_service:
  endGoal_stopTime: 0.0        # 到达目标点后停留时间
  path_file_name: "prior_path.yaml" # 先验路径文件名
