<!-- 模拟底盘运动 -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">
    <xacro:include filename="property.xacro" />
    <link name="${ns}chassis">
        <visual>
            <origin xyz="0 ${(holder_length)/2} 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${holder_radius}" length="${holder_length}" />
            </geometry>
        </visual>
        <!-- <collision>
            <geometry>
                <cylinder radius="${holder_radius}" length="${holder_length}" />
            </geometry>
        </collision> -->
        <xacro:cylinder_inertial_matrix m="0.00001" r="${holder_radius}" h="${holder_length}" />
    </link>

    <gazebo reference="${ns}chassis">
        <gravity>0</gravity>
    </gazebo>
</robot>